'use client';

import { Box, Text, Textarea } from '@chakra-ui/react';

const TermsOfUse = () => {
  const data = `
PIBOOGO, TERMS OF SERVICE

Last Updated: March 1, 2025


1. Overview and Acceptance of Use
Welcome to PIBOOGO! PIBOOGO Wholesale, (“PIBOOGO”) is a curated wholesale online marketplace connecting creative brands with retailers, accessible through its websites (collectively, the “Site”) and mobile applications (collectively, the “Application”) (together, the “Services”). Throughout these Terms of Service (“Terms”), the terms “PIBOOGO”, “our”, “us”, and/or “we” refer to PIBOOGO. The terms “you” and/or “your” refer to any visitor of the Site and/or the Application and any user of the Services, including any Member (as defined below). These Terms govern your access to and use of the Services and Collective Content (defined below) and constitute a binding legal agreement between you and PIBOOGO.
Please read these Terms, our Privacy Policy, the Retailer Terms of Service, and Brand Terms of Service, all of which are incorporated herein by reference and govern your access to and use of the Services. The Services are offered and available solely to users who are 18 or older. By using the Services, you represent and warrant that you are of legal age to form a binding contract with PIBOOGO and meet the foregoing eligibility requirements. If you do not meet these requirements, you must not access or use the Services. If you are entering into these Terms on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that party to these Terms and, in such event, “you” and “your” will refer and apply to that party.
YOU ACKNOWLEDGE AND AGREE THAT BY ACCESSING OR USING THE SERVICES (INCLUDING BY DOWNLOADING OR POSTING ANY CONTENT FROM OR ONTO THE SERVICES), YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OTHER TERMS AND POLICIES REFERENCED IN THESE TERMS. THIS APPLIES WHETHER OR NOT YOU HAVE REGISTERED ON OR THROUGH THE SERVICES. IF YOU DO NOT AGREE, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SERVICES OR COLLECTIVE CONTENT.
THESE TERMS REQUIRE THE USE OF ARBITRATION TO RESOLVE INDIVIDUAL DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU SHOULD THERE BE A DISPUTE. YOUR AGREEMENT TO THESE TERMS INDICATES YOUR EXPRESS ACKNOWLEDGEMENT AND AGREEMENT THAT YOU HAVE READ AND UNDERSTAND HOW THE ARBITRATION PROVISION SET FORTH IN SECTION 28 BELOW WORKS.

2. Modification
We reserve the right, at our sole discretion, to modify, suspend, discontinue, or terminate the Services or any content, feature, or material we provide thereon, or to modify these Terms, at any time and without prior notice. We have no obligation to update any information on the Services. We will not be liable if, for any reason, all or any part of the Services is unavailable at any time or for any period. From time to time, we may restrict access to some or all parts of the Services to users, including Retailers and Brands.
You agree that it is your responsibility to monitor changes to our Services. If we modify these Terms, we will post the modification on the Site or via the Application and/or provide you with notice of the modification. By continuing to access or use the Services thereafter, you are indicating that you agree to be bound by the modified Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Services.

3. Key Definitions
“Collective Content” means, collectively, PIBOOGO Content and Member Content.
“Content” means text, graphics, images, music, software (excluding the Application), audio, video, information, or other materials.
“PIBOOGO Content” means Content that PIBOOGO makes available through the Services including any Content licensed from a third party, but excluding Member Content.
“Member” means any Retailer or Brand that completes PIBOOGO’s account registration process, as described under the “Account Registration” section below. A Retailer is a business that purchases goods through the Services for resale, while a Brand is a business that sells goods through the Services to Retailers.
“Member Content” means Content that a member (whether a Retailer or a Brand) posts, uploads, publishes, submits, or transmits to PIBOOGO to be made available through the Services.

4. Account Registration
To access certain features of the Services and to post any Member Content thereon, you must register to create an account (“Account”) and become a member. PIBOOGO offers two types of Accounts:
Retailer Account: This account is for Retailers, who are businesses that purchase goods through the Services for the purpose of resale. Retailer Accounts provide access to purchase products and other services tailored to Retailers.
Brand Account: This account is for Brands, who are businesses that offer to sell and/or sell their goods to Retailers through Services. Brand Accounts provide access to list and manage products and other services tailored to Brands.
Each type of Account gives access to different aspects of the Services.
You may register directly via the Site or Application. During the registration process, you will be required to provide certain information (depending on the type of Account), and you will establish a username and a password. You agree that all information you provide to register for an Account (and/or for any subsequent activity or interaction with PIBOOGO and the Services), including through the use of any interactive features on the Services, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information or information you provide, consistent with our Privacy Policy.
You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. We reserve the right to temporarily suspend or permanently terminate your Account if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete. You are responsible for safeguarding your password and you agree that you will not disclose it to any third party. You agree that you are solely responsible for any activities or actions under your Account, whether you authorized them or not. You will immediately notify us of any unauthorized use of your Account. We have the right to disable any username, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms.

5. Account Levels
Brand Account. To sell goods through the Services as a Brand, you must submit an application to, and be approved by, PIBOOGO. The application process and Brand Account are both free. The application seeks basic information about you, your company, and your products. If approved as a Brand, you will be required to submit additional information, including about your business, where to deposit funds from sales of your products, and applicable tax and related documentation (e.g., EIN, W-8, etc.). Additional details regarding information collected can be found in our Privacy Policy. For clarity, your use of the Services as a Brand is subject to the Brand Terms of Service referenced above.
Retailer Account. To purchase goods through the Services as a Retailer, you need to establish a Retailer Account, which is free. When you sign up as a Retailer, you will be required to submit customary information such as your first and last name, store type (e.g., online, brick & mortar), email address, and other information about your business. Before you make your first purchase as a Retailer, you may be required to provide additional information such as payment method information, reseller ID number, and related documentation, and any other information as may be required by PIBOOGO. Additional details regarding information collected can be found in our Privacy Policy. For clarity, your use of the Services as a Retailer is subject to the Retailer Terms of Service referenced above.
You acknowledge and agree that by submitting your application to become a Retailer, you authorize PIBOOGO and its designated agents to access your personal and business credit history, including obtaining a consumer credit report, for the purpose of evaluating your eligibility for a line of credit with PIBOOGO. You further understand that credit inquiries may impact your credit score.
By submitting payment details in conjunction with registering for a Retailer Account and/or purchasing goods, you agree to pay for the goods purchased and any applicable taxes and other fees that may accrue, and authorize us to charge the payment method with the information you have supplied to us, and/or to credit such payment method to make any adjustments if necessary. We reserve the right to correct any errors in pricing. We, and the Brand, have the right to refuse any order.

6. Ownership
The Services and Collective Content are protected by copyright, trademark, and other intellectual property laws of the United States and foreign countries. You acknowledge and agree that the Services and Collective Content, excluding your specific Member Content (as defined below), including all associated intellectual property rights, are the exclusive property of PIBOOGO, its licensors, and/or other content providers. Except as expressly stated in these Terms, no implied licenses are granted under these Terms.
You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services or Collective Content. Additionally, PIBOOGO owns all pending, registered, and unregistered trademarks, trade dress, and trade names appearing on the Services, including the PIBOOGO name and logo, and all related names, logos, product and service names, designs, and slogans. You agree not to use any of these marks without PIBOOGO’s prior written consent.
All other trademarks, service marks, logos, trade names, and other proprietary designations used on the Services are the trademarks or registered trademarks of their respective owners.

7. License Granted by PIBOOGO
a. License Grant. Subject to the terms and conditions of these Terms, PIBOOGO grants you:
(a) a non-transferable, non-exclusive, revocable, limited license, with no right to sublicense, to use and access the Services, and to view any Collective Content to which you are permitted access solely for the purposes set forth in these Terms; and
(b) a limited non-exclusive, revocable, non-transferable license to download and install a copy of the Application on your device solely in connection with your use of the Services.
b. Restrictions. Except as otherwise stated, the rights granted herein are subject to the following restrictions:
(a) you shall not license, sell, rent, lease, transfer, assign, distribute, host or otherwise commercially exploit the Services or Collective Content;
(b) you shall not copy, reproduce, disseminate, distribute, modify, adapt, create derivative works of, publicly display, publicly perform, stream, broadcast, republish, download, disassemble, reverse compile, reverse engineer, store, post or transmit any of the material or content on our Services; and
(c) you shall not interfere with or circumvent any feature of the Services, including any security or access control mechanism, in whole or in part, except as permitted in these Terms.
Except as expressly granted in these Terms, no licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by PIBOOGO, its licensors, or others. If you violate the rights of PIBOOGO, its licensors, or others, your right to use the Services will stop immediately and you must, at our option, return or destroy any copies of the materials you have made.

8. License Granted by Member
To get the most out of the Services, Members can provide or otherwise make Member Content available to us for use in connection with the Services. For these purposes, you hereby grant to PIBOOGO a worldwide, perpetual, non-exclusive, transferable, sublicensable, royalty-free license to use, view, copy, adapt, modify, distribute, publicly display and publicly perform (through any means necessary) such Member Content on, through or by means of the Services and/or any of PIBOOGO’s advertising, marketing, publicity, or other initiatives or events. PIBOOGO does not claim any ownership rights in any Member Content and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit any Member Content.
You acknowledge and agree that you are solely responsible for all Member Content that you make available through the Services. Accordingly, you represent and warrant that:
(a) you either are the sole and exclusive owner of all such Member Content or you have all rights, licenses, consents, and releases necessary to grant to PIBOOGO the rights in such Member Content as contemplated under these Terms; and
(b) neither the Member Content nor any portion thereof, nor your posting, uploading, publication, submission or transmittal of the Member Content, nor PIBOOGO’s use of the Member Content (or any portion thereof) on, through or by means of the Services and/or third-party platforms, will infringe, misappropriate, or violate a third party’s patent, copyright, trademark, trade secret, moral rights, or other intellectual property rights, or rights of publicity or privacy, or contain libelous, misleading, or otherwise unlawful, abusive, harassing, or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Services, or result in the violation of any applicable law or regulation. You agree that you will not use a false e-mail address, pretend to be someone other than yourself or otherwise mislead us or third parties as to the origin of any posts. You are solely responsible for any Member Content you make and its accuracy. PIBOOGO takes no responsibility and assumes no liability for any Member Content posted by you or any third party, and you agree to indemnify PIBOOGO per the terms of the Indemnification section herein.

9 . Feedback
We welcome and encourage you to provide feedback, comments, and suggestions for improvements to the Services (“Feedback”). You acknowledge and agree that if you submit any Feedback to us (through any communication channel), you hereby grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully paid, royalty-free, sub-licensable, and transferable license to use, copy, modify, create derivative works based upon, and otherwise exploit the Feedback solely for the purpose of improving the Services.

10. Reliance on Information Posted
The information presented on or through the Services is made available solely for general informational purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you, any other visitor to the Site, user of the Services, or anyone who may be informed of any of its contents.
The Services may include content provided by third parties, including materials from other users, Members, bloggers, and third-party licensors. All statements and opinions expressed in these materials, including articles, responses to questions, and other content, other than the content provided by PIBOOGO, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinions of PIBOOGO. We are not responsible, nor liable to you or any third party, for the content or accuracy of any materials provided by any third parties.


11. Links to Third Party Websites
The Services may contain links to third-party websites or resources. You acknowledge and agree that PIBOOGO is not responsible or liable for: (a) the availability or accuracy of such websites or resources; or (b) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by PIBOOGO of such websites, resources, or the content, products, or services available therefrom. You acknowledge that you are solely responsible for, and assume all risks arising from, your use of any such websites or resources, or the content, products, or services available therefrom. Additionally, Apple Inc. (“Apple”) and Google, Inc. (“Google”) will be third-party beneficiaries to these Terms if you access the Services using applications developed for Apple iOS or Android, respectively. These third-party beneficiaries are not parties to these Terms and are not responsible for the provision or support of the Services in any manner. Your access to the Services through these applications or devices is subject to the respective terms of service and privacy policies of Apple and Google.

12. Notice Regarding Apple
This Section only applies to the extent you are using our mobile application on an iOS device. You acknowledge that these Terms are between you and PIBOOGO only, not with Apple, and Apple is not responsible for the Services or the content thereof. Apple has no obligation to furnish any maintenance and support services with respect to the Services. If the Services fail to conform to any applicable warranty, you may notify Apple, and Apple will refund any applicable purchase price for the mobile application to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation with respect to the Services. Apple is not responsible for addressing any claims by you or any third party relating to the Services or your possession and/or use of the Services, including: (a) product liability claims; (b) any claim that the Services fail to conform to any applicable legal or regulatory requirement; or (c) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement, and discharge of any third-party claim that the Services and/or your possession and use of the Services infringe a third party’s intellectual property right. You agree to comply with any applicable third-party terms when using the Services. Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms.

13. Prohibited Uses
You agree not to do any of the following
Post, upload, publish, submit or transmit any Content that: (a) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (b) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (c) is fraudulent, false, misleading or deceptive; (d) is defamatory, obscene, pornographic, vulgar or offensive; (e) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (f) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (g) promotes illegal or harmful activities or substances.
Use, embed, display, mirror or frame the Site or Application, or any individual element within the Services, PIBOOGO’s name, any PIBOOGO trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without PIBOOGO’s express written consent or as enabled by features made available by PIBOOGO (e.g., widgets) (you may link to PIBOOGO’s homepage, so long as you do not imply or suggest any form of association, approval or endorsement on our behalf without our express written consent but you may not link to the Site in a libelous, misleading or otherwise unlawful manner, or in any manner that violates these Terms);
Access, tamper with or use non-public areas of the Site or Application, PIBOOGO’s computer systems or the technical delivery systems of PIBOOGO’s providers;
Attempt to probe, scan, or test the vulnerability of any PIBOOGO system or network or breach any security or authentication measures;
Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by PIBOOGO or any of PIBOOGO’s providers or any other third party (including another user) to protect the Services or Collective Content;
Attempt to access or search the Services or Collective Content or download Collective Content from the Services through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by PIBOOGO or other generally available third-party web browsers;
Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation to, through, or with any assistance from, the Services;
Use any meta tags or other hidden text or metadata utilizing a PIBOOGO trademark, logo URL or product name without PIBOOGO’s express written consent;
Use the Services or Collective Content in any manner not permitted by these Terms;
Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Collective Content to send altered, deceptive or false source-identifying information;
Attempt to decipher, decompile, disassemble or reverse engineer any of the software or algorithms used to provide the Services or Collective Content;
Interfere with, or attempt to interfere with, the access of any user, host or network, including sending a virus, overloading, flooding, spamming or mail-bombing the Services;
Collect or store any personally identifiable information from the Services from other users of the Site, Services or Application without their express permission and in a manner that does not violate PIBOOGO’s Privacy Policy;
Impersonate or misrepresent your affiliation with any person or entity;
Violate any applicable law or regulation; or
Encourage or enable any other third party to do any of the foregoing.
PIBOOGO will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. PIBOOGO may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms. You acknowledge that PIBOOGO has no obligation to monitor your access to or use of the Services or Collective Content, or to review or edit any Collective Content, but has the right to do so for the purpose of operating the Services, to ensure your compliance with these Terms, to investigate a complaint or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. PIBOOGO reserves the right, at any time and without prior notice, to remove or disable access to any Member Content or Collective Content that PIBOOGO, in its sole discretion, considers to be in violation of these Terms or otherwise harmful to the Services. PIBOOGO reserves the right to cooperate fully with law enforcement, and to involve and share information with law enforcement, governmental agencies or other oversight bodies if PIBOOGO suspects illegal activity may be taking place.

14. Text Messages and Telephone Calls
PIBOOGO, and those acting on PIBOOGO’s behalf, may contact you by telephone or text message (including through use of an automatic telephone dialing system) at the phone numbers you have provided to us. By providing your phone number, you consent to receiving automated messages, which you can opt-out of at any time. These messages may include operational messages about your use of the Service. 
You understand that you are not required to consent to communications as a condition of purchasing any property, goods, or services. You may opt out of receiving telephone calls or text messages from us at any time, either by texting the word “STOP” in response to a text message received from us using the mobile device that is receiving the messages. You may continue to receive text messages for a short period while PIBOOGO processes your request, and you may also receive text messages confirming the receipt of your opt-out request. 
Opting out of receiving operational text messages may impact the functionality of the Services. Standard data and message rates may apply whenever you send or receive such messages, as specified by your carrier.

15. Procedure for Claiming Intellectual Property Infringement – DMCA Notice
PIBOOGO respects intellectual property laws and expects its users to do the same. It is PIBOOGO’s policy to terminate, in appropriate circumstances, Members or other account holders who infringe or are believed to be infringing the intellectual property rights of others. Click here for PIBOOGO’s Copyright & IP Policy.

16. Information We Collect About You
All information we collect about you when you apply for an account or use or visit the Services is subject to our Privacy Policy. By using the Services, you consent to the terms and conditions of the Privacy Policy and all actions taken by us in accordance with it.

17. Termination and Account Cancellation
If you breach any of these Terms, PIBOOGO will have the right to suspend or disable your Account or terminate these Terms, in its sole discretion and without prior notice to you. PIBOOGO reserves the right to revoke your access to and use of the Services and Collective Content at any time, with or without cause. In the event PIBOOGO terminates these Terms for your breach, you will remain liable for all amounts due hereunder. You may cancel your Account at any time by contacting us.

18. Disclaimers
The Services and Collective Content are provided “as is”, without warranty of any kind, either express or implied. Without limiting the foregoing, PIBOOGO explicitly disclaims any warranties of merchantability, fitness for a particular purpose, quiet enjoyment or non-infringement, and any warranties arising out of course of dealing or usage of trade. PIBOOGO makes no warranty that the Services or Collective Content will meet your requirements or be available on an uninterrupted, secure or error-free basis. PIBOOGO makes no warranty regarding the quality of any products, services or Collective Content purchased or obtained through the Services or the accuracy, timeliness, truthfulness, completeness or reliability of any content obtained through the Services. No advice or information, whether oral or written, obtained from PIBOOGO or through the Services or Collective Content, will create any warranty not expressly made herein.
You are solely responsible for all of your communications and interactions with other users of the Services and with other persons with whom you communicate or interact as a result of your use of the Services. You understand that PIBOOGO does not screen or inquire into the background of any users of the Services, nor does PIBOOGO make any attempt to verify the statements of users of the Services. PIBOOGO makes no representations or warranties as to the conduct of users of the Services or their compatibility with any current or future users of the Services. You agree to take reasonable precautions in all communications and interactions with other users of the Services and with other people with whom you communicate or interact because of your use of the Services, particularly if you decide to meet offline or in person.

19. Indemnity
You agree to defend, indemnify, and hold PIBOOGO, and its parent, subsidiaries, affiliates, partners, successors, and assigns, and each of their owners, members, officers, directors, employees, agents, representatives, contractors, subcontractors, licensors, service providers, and third-party content providers harmless from any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable legal and accounting fees) made by any third party due to or arising out of your violation of these Terms, and/or any law or the rights of a third party, and/or your use of the Services, including your Member Content.

20. Limitation of Liability
You acknowledge and agree that, to the maximum extent permitted by law, the entire risk arising out of your access to and use of the Services and Collective Content remains with you. Neither PIBOOGO nor any other person or entity involved in creating, producing, or delivering the Site, Services, Application, or Collective Content will be liable for any incidental, special, exemplary, or consequential damages, including lost profits, loss of data or goodwill, service interruption, computer damage, or system failure or the cost of substitute products or services, or for any damages for personal or bodily injury or emotional distress arising out of or in connection with these Terms or from the use of or inability to use the Services or Collective Content, or from any communications, interactions, or meetings with other users of the Services or other persons with whom you communicate or interact as a result of your use of the Services, whether based on warranty, contract, tort (including negligence), product liability, or any other legal theory, and whether or not PIBOOGO has been informed of the possibility of such damage, even if a limited remedy set forth herein is found to have failed of its essential purpose.
In no event will PIBOOGO aggregate liability arising out of or in connection with these Terms or from the use of or inability to use the Services or Collective Content exceed US$100. The limitations of damages set forth above are fundamental elements of the basis of the bargain between PIBOOGO and you. Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, so the above limitation may not apply to you.

21. Controlling Law and Jurisdiction
These Terms and any action related thereto will be governed by the applicable laws of the State of California, United States, without regard to its conflict of law’s provisions. The exclusive jurisdiction and venue of any action or court proceeding permitted under these Terms will be the state and federal courts located in the Northern District of California, United States. Each of the parties hereto waives any objection to jurisdiction and venue in such courts. However, if you are located outside of the United States, the parties agree that any dispute, controversy, or claim arising out of or relating to these Terms may be subject to alternative dispute resolution mechanisms, such as arbitration, as mutually agreed by both parties.

21. Controlling Law and Jurisdiction
These Terms and any action related thereto will be governed by the applicable laws of the State of California, United States, without regard to its conflict of law’s provisions. The exclusive jurisdiction and venue of any action or court proceeding permitted under these Terms will be the state and federal courts located in the Northern District of California, United States, unless you are in South Korea, in which case the jurisdiction and venue will be the courts located in Seoul, South Korea. Each of the parties hereto waives any objection to jurisdiction and venue in such courts.
In the event of a dispute, controversy, or claim arising out of or relating to these Terms, the parties agree to first attempt resolution through informal negotiations. If informal negotiations fail, the dispute may be resolved through alternative dispute resolution mechanisms such as arbitration, which may be conducted in California or South Korea depending on the location of the parties involved, as mutually agreed by both parties.

22. Export Control
You agree to comply fully with all applicable U.S. and foreign export laws and regulations, including but not limited to the U.S. Export Administration Regulations (EAR), International Traffic in Arms Regulations (ITAR), and any other relevant trade restrictions, to ensure that neither the Application nor any technical data related thereto, nor any direct product thereof, is exported, re-exported, or made available directly or indirectly in violation of such laws and regulations.
You represent and warrant that: (a) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, nor are you located in any other country subject to applicable export restrictions; (b) you are not listed on any U.S. Government list of prohibited or restricted parties, including but not limited to the Specially Designated Nationals (SDN) list, the Entity List, or the Denied Persons List.
In the case of transactions involving products originating from South Korea and being exported to the United States, you acknowledge and agree to comply with all relevant export control regulations from both the United States and South Korea, including any restrictions on re-exportation to other countries, as applicable.

23. Assignment
You may not assign or transfer these Terms, by operation of law or otherwise, without PIBOOGO's prior written consent. Any attempt by you to assign or transfer these Terms without such consent will be null and void. PIBOOGO may assign or transfer these Terms in its sole discretion without restriction, including but not limited to, to any of its affiliates, subsidiaries, or successors. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors, permitted assigns, and any legal entity to whom rights or obligations under these Terms may be transferred.

24. Notices
Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given:
(a) by PIBOOGO via email (to the primary account email address that you have provided to us);
(b) by posting to the Site;
(c) via the Application;
(d) by any other means permitted by applicable law, including but not limited to, social media, direct messages, or other electronic communication channels.
For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted. For notices made through the Site or Application, the date of receipt will be deemed the date on which the notice is posted or made available to you.

25. Confidentiality
“Confidential Information” means any PIBOOGO business or technical information that is disclosed to you in connection with your use of the Services, including any information relating to PIBOOGO’s plans, designs, technical features, business opportunities, or know-how. Confidential Information excludes any information that:
(a) is or becomes generally known to the public other than as a result of your breach of these Terms; (b) is rightfully known to you at the time of disclosure without restrictions on use or disclosure; (c) is independently developed by you, without access to or use of any Confidential Information; or (d) is rightfully obtained by you from a third party, who has the right to disclose it and who discloses it without restrictions on use or disclosure.
Except as otherwise required by law, you will maintain all Confidential Information in strict confidence and will not use any Confidential Information except solely as necessary to use the Services. You agree to protect Confidential Information from unauthorized use and disclosure using efforts equivalent to the efforts that you ordinarily use with respect to your own confidential information and in no event less than a reasonable standard of care. Confidential Information may be disclosed to the extent necessary to comply with any court-ordered or governmental or legal requirement, but you must not disclose more Confidential Information than necessary to comply with any such requirement. You must inform the party to whom you are disclosing the Confidential Information that it is confidential and seek to seal the Confidential Information if possible; and, to the extent not prohibited by law, you must provide PIBOOGO with advanced notice of no less than 14 days prior to disclosing the Confidential Information and provide sufficient information to PIBOOGO that PIBOOGO may intervene and seek a protective order if PIBOOGO wishes to prevent disclosure.

26. Interactive Chat and Virtual Assistants
Some of the Services may have chat, live support, instant messaging, or similar functionality to serve you better (“Chats”). Chats may allow you to speak to a human representative, a Virtual Assistant (as defined below), or some combination of the two. You should review our Privacy Policy to learn how we treat information that could identify you gathered via a Chat. Please be aware that communications may be monitored for quality assurance and other purposes. We strive to provide accurate information through the Chats; however, we cannot guarantee the accuracy, completeness, or up-to-date nature of the information provided. Chats may not always be available or error-free. Chats may be provided by third parties, and you may be entering into a contractual agreement with those third parties when you use the Chat. You should refer to the applicable Chat and its hyperlinks to learn more.
Chats may use interactive, automated computer programs and similar technologies to provide customer service via the Chat (“Virtual Assistants”). Virtual Assistants often work by using “natural language processing” technology to understand your questions and inputs and respond to them with relevant information or follow-up inquiries. Our Virtual Assistants typically identify that you are interacting with a computer program and not a human, sometimes by a “Powered by…” or a similar legend in the Chat or by setting up the Chat in such a way that it is apparent that a Virtual Assistant is used. Virtual Assistants use technology to respond to your input without human intervention. Although Virtual Assistants are automated, your inputs and responses may be viewed and accessed by real people, possibly in real time. Be aware that some Virtual Assistants may connect you to one of our human representatives.
Virtual Assistants may in some instances provide responses that are inaccurate, inapplicable, or inappropriate. You understand that Virtual Assistants’ responses are intended to be suggestions for your consideration only and you agree that you will exercise reasonable discretion before relying on any Virtual Assistant’s response. We are not liable for any damage or losses incurred as a result of using any Virtual Assistant’s responses. A Virtual Assistant's response does not necessarily represent the opinion, comment, content, or recommendation of PIBOOGO.
DISCLAIMER: All content, suggestions, and output provided by a Virtual Assistant should be verified for accuracy. Any Virtual Assistant is provided for convenience only and you should not rely on the information from the Virtual Assistant without further verification from an official source. PIBOOGO makes no representation or warranty concerning the reliability, appropriateness, completeness, applicability, or accuracy of any Virtual Assistant or any Virtual Assistant’s response.

28. Dispute Resolution – Arbitration 
PLEASE READ THIS ARBITRATION PROVISION CAREFULLY BECAUSE IT AFFECTS YOUR RIGHTS.
You and PIBOOGO agree that any dispute, claim, or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation, or validity thereof, or the use of the Services (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right to:
(a) bring an individual action in small claims court;
(b) the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party’s copyrights, trademarks, trade secrets, patents, or other intellectual property rights;
(c) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; and
(d) seek injunctive relief in a court of law in aid of arbitration.
For international transactions between a Korean exporter and a U.S. seller using PIBOOGO, the parties acknowledge and agree that the law of the state of California will apply, and all disputes will be handled under the applicable arbitration rules outlined in this agreement.
YOU ACKNOWLEDGE AND AGREE THAT YOU AND PIBOOGO ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING. Further, unless both you and PIBOOGO otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.
Arbitration Rules and Governing Law The arbitration will be administered by the American Arbitration Association (“AAA”) in accordance with the Commercial Arbitration Rules (the “AAA Rules”) then in effect, except as modified by this “Dispute Resolution” section. The parties agree that the Federal Arbitration Act applies and will govern the interpretation and enforcement of this Arbitration Agreement. However, for disputes involving international trade between Korean and U.S. parties, the applicable international trade law and treaties may also be considered.
Arbitration Process A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. The arbitrator will be either a retired judge or an experienced (15+ years practicing) attorney licensed to practice law in the state of California. Disputes related to international trade between Korea and the U.S. will take into account the relevant cross-border trade regulations.
Arbitration Location and Procedure Unless you and PIBOOGO otherwise agree, the arbitration will be conducted in the county where you reside. For international disputes between a Korean exporter and a U.S. seller, the arbitration will take place in California, where PIBOOGO is based, unless otherwise agreed. If your claim does not exceed US$10,000, then the arbitration will be conducted solely based on documents you and PIBOOGO submit to the arbitrator, unless you request a hearing, or the arbitrator determines that a hearing is necessary. If your claim exceeds US$10,000, your right to a hearing will be determined by the AAA Rules.
Arbitrator’s Decision The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator’s award damages must be consistent, to the extent permitted by law, with the terms of the “Limitation of Liability” section above as to the types and the amounts of damages for which a party may be held liable.
Fees Your responsibility to pay any AAA filing, administrative, and arbitrator fees will be solely as set forth in the AAA Rules. If applicable arbitration rules or laws require PIBOOGO to pay a greater portion or all such fees and costs for this Dispute Resolution provision to be enforceable, then PIBOOGO will have the right to elect to pay the fees and costs and proceed to arbitration.
Changes Notwithstanding the provisions of the “Modification” section above, if PIBOOGO changes this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending PIBOOGO written notice (including by contacting PIBOOGO) within 30 days of the date such change became effective, as indicated in the “Last Updated Date” above or in the date of PIBOOGO’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and PIBOOGO in accordance with the arbitration provisions of this “Dispute Resolution” section (however entitled) as of the date you first accepted these Terms or accepted any subsequent changes to these Terms.
29. Entire Agreement 
These Terms constitute the entire and exclusive understanding and agreement between PIBOOGO and you regarding the Services and Collective Content, and these Terms supersede and replace all prior oral or written understandings or agreements between PIBOOGO and you regarding the Services and Collective Content.

30. Miscellaneous 
The failure by PIBOOGO to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of PIBOOGO. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible, and the other provisions of these Terms will remain in full force and effect. Throughout these Terms, the word “includes” or “including” means “including, but not limited to.” Provisions that by their nature are intended to survive the termination of these Terms or your use of the Services will survive.

31. Contact Us (연락처)
If you have any questions about these Terms, please contact PIBOOGO at: 00000@gmail.com
`;

  return (
    <Box w={'100%'} bg={'#8C644212'}>
      <Textarea
        readOnly
        border={0}
        h={'400px'}
        resize={'none'}
        overflowY={'auto'}
        color={'#556A7E'}
        fontSize={'1rem'}
        fontWeight={500}
        lineHeight={'1.75rem'}
        value={data}
      />
    </Box>
  );
};

export default TermsOfUse;
