export const ERR_INFO = {
  ACC: {
    NOT_FOUND_EMAIL: {
      CODE: 10001,
      KEY: 'NOT_FOUND_EMAIL',
      KR: '이메일을 입력해주세요.',
      EN: 'Please enter your email.',
      ZH: '请输入您的电子邮件。',
      ES: 'Por favor ingrese su correo electrónico。',
    },
    NOT_MATCH_EMAIL: {
      CODE: 10002,
      KEY: 'NOT_MATCH_EMAIL',
      KR: '이메일 형태를 확인해주세요.',
      EN: 'Please check the email.',
      ZH: '请检查电子邮件。',
      ES: 'Por favor revise el correo electrónico。',
    },
    CHECK_USER_INFO: {
      CODE: 10003,
      KEY: 'CHECK_USER_INFO',
      KR: '아이디 또는 비밀번호를 확인해주세요.',
      EN: 'Please check your ID or password.',
      ZH: '请检查您的ID或密码。',
      ES: 'Por favor revise su ID o contraseña。',
    },

    NOT_FOUND_PASSWORD: {
      CODE: 10004,
      KEY: 'NOT_FOUND_PASSWORD',
      KR: '비밀번호를 입력해주세요.',
      EN: 'Please enter your password.',
      ZH: '请输入您的密码。',
      ES: 'Por favor ingrese su contraseña。',
    },
    NOT_MATCH_PASSWORD: {
      CODE: 10005,
      KEY: 'NOT_MATCH_PASSWORD',
      KR: '비밀번호를 확인해주세요.',
      EN: 'Please check the password.',
      ZH: '请检查密码。',
      ES: 'Por favor revise la contraseña。',
    },
    NOT_FOUND_OLD_PASSWORD: {
      CODE: 10006,
      KEY: 'NOT_FOUND_OLD_PASSWORD',
      KR: '기존 비밀번호를 입력해주세요.',
      EN: 'Please enter your old password.',
      ZH: '请输入您的旧密码。',
      ES: 'Por favor ingrese su contraseña anterior。',
    },
    NOT_MATCH_OLD_PASSWORD: {
      CODE: 10007,
      KEY: 'NOT_MATCH_OLD_PASSWORD',
      KR: '기존 비밀번호를 확인해주세요.',
      EN: 'Please check your old password.',
      ZH: '请检查您的旧密码。',
      ES: 'Por favor revise su contraseña anterior。',
    },
    NOT_FOUND_NEW_PASSWORD: {
      CODE: 10008,
      KEY: 'NOT_FOUND_NEW_PASSWORD',
      KR: '새로운 비밀번호를 입력해주세요.',
      EN: 'Please enter a new password.',
      ZH: '请输入新密码。',
      ES: 'Por favor ingrese una nueva contraseña。',
    },
    NOT_MATCH_NEW_PASSWORD: {
      CODE: 10009,
      KEY: 'NOT_MATCH_NEW_PASSWORD',
      KR: '새로운 비밀번호를 확인해주세요.',
      EN: 'Please check the new password.',
      ZH: '请检查新密码。',
      ES: 'Por favor revise la nueva contraseña。',
    },
    NOT_MATCH_NEW_PASSWORD_CHECK: {
      CODE: 10010,
      KEY: 'NOT_MATCH_NEW_PASSWORD_CHECK',
      KR: '새로운 비밀번호가 일치하지 않습니다.',
      EN: 'New password does not match.',
      ZH: '新密码不匹配。',
      ES: 'La nueva contraseña no coincide.',
    },

    NOT_FOUND_NAME: {
      CODE: 10011,
      KEY: 'NOT_FOUND_NAME',
      KR: '이름을 입력해주세요.',
      EN: 'Please enter your name.',
      ZH: '请输入您的姓名。',
      ES: 'Por favor ingrese su nombre。',
    },
    NOT_FOUND_PHONE: {
      CODE: 10012,
      KEY: 'NOT_FOUND_PHONE',
      KR: '전화번호를 입력해주세요.',
      EN: 'Please enter your phone.',
      ZH: '请输入您的电话。',
      ES: 'Por favor ingrese su teléfono。',
    },

    NOT_MATCH_PHONE: {
      CODE: 10013,
      KEY: 'NOT_MATCH_PHONE',
      KR: '전화번호를 확인해주세요.',
      EN: 'Please check the phone.',
      ZH: '请检查电话。',
      ES: 'Por favor revise el teléfono。',
    },

    NOT_SELECT_BUSINESS_TYPE: {
      CODE: 10014,
      KEY: 'NOT_FOUND_BUSINESS_TYPE',
      KR: '사업자 업종을 선택해주세요.',
      EN: 'Please select your business type.',
      ZH: '请选择您的业务类型。',
      ES: 'Por favor seleccione su tipo de negocio。',
    },
    NOT_FOUND_BUSINESS_NUMBER: {
      CODE: 10015,
      KEY: 'NOT_FOUND_BUSINESS_NUMBER',
      KR: '사업자번호를 입력해주세요.',
      EN: 'Please enter your business number.',
      ZH: '请输入您的营业执照号码。',
      ES: 'Por favor ingrese su número de negocio。',
    },

    NOT_FOUND_VERIFICATION_CODE: {
      CODE: 10016,
      KEY: 'NOT_FOUND_VERIFICATION_CODE',
      KR: '인증번호를 입력해주세요.',
      EN: 'Please enter your verify code.',
      ZH: '请输入您的验证码。',
      ES: 'Por favor ingrese su código de verificación。',
    },

    NOT_FOUND_ZIP_CODE: {
      CODE: 10017,
      KEY: 'NOT_FOUND_ZIP_CODE',
      KR: '우편번호를 입력해주세요.',
      EN: 'Please enter your zip code.',
      ZH: '请输入您的邮政编码。',
      ES: 'Por favor ingrese su código postal.',
    },
    NOT_FOUND_CITY: {
      CODE: 10018,
      KEY: 'NOT_FOUND_CITY',
      KR: '도시를 입력해주세요.',
      EN: 'Please enter your city.',
      ZH: '请输入您的城市。',
      ES: 'Por favor ingrese su ciudad。',
    },
    NOT_FOUND_STATE: {
      CODE: 10019,
      KEY: 'NOT_FOUND_STATE',
      KR: '우편번호를 입력해주세요.',
      EN: 'Please enter your state.',
      ZH: '请输入您的州。',
      ES: 'Por favor ingrese su estado.',
    },
    NOT_FOUND_ADDRESS: {
      CODE: 10020,
      KEY: 'NOT_FOUND_ADDRESS',
      KR: '주소를 입력해주세요.',
      EN: 'Please enter your address.',
      ZH: '请输入您的地址。',
      ES: 'Por favor ingrese su dirección.',
    },
  },
  SERVICE: {
    NOT_SERVICE: {
      CODE: 20000,
      KEY: 'NOT_SERVICE',
      KR: '현재 서비스를 지원하지 않습니다.',
      EN: 'This service is not supported.',
      ZH: '此服务不受支持。',
      ES: 'Este servicio no es compatible.',
    },
    NOT_SERVICE_PAYMENT: {
      CODE: 20000,
      KEY: 'NOT_SERVICE_PAYMENT',
      KR: '현재 해당 결제서비스를 지원하지 않습니다.',
      EN: 'We do not currently support that payment service.',
      ZH: '我们目前不支持该支付服务。',
      ES: 'Actualmente no admitimos ese servicio de pago.',
    },
    NOT_SELECTED: {
      CODE: 20001,
      KEY: 'NOT_SELECTED',
      KR: '상품을 선택해주세요.',
      EN: 'Please select the product.',
      ZH: '请选择产品。',
      ES: 'Por favor seleccione el producto.',
    },
  },
};
